services:
    ufo_api_server.zend_json_rpc_server_facade:
        class: Ufo\JsonRpcBundle\Facade\ZendJsonRpcServerFacade
        arguments: ['@router', '%kernel.environment%']

    ufo_api_service.ping:
        class: Ufo\JsonRpcBundle\ApiMethod\PingProcedure
        tags:
            - { name: rpc.service, priority: 100  }
